/// Flutter icons Binder
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Binder
///      fonts:
///       - asset: fonts/Binder.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Binder {
  Binder._();

  static const _kFontFam = 'Binder';
  static const String? _kFontPkg = null;

  static const IconData binder = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
